buildscript {

    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:9.0.1'
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:2.4.20'
    }
}

plugins {
    id 'com.google.devtools.ksp' version '2.3.12' apply false
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url("https://jitpack.io") }
    }
}

tasks.register('clean', Delete) {
    delete rootProject.buildDir
}