plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.parcelize)
    alias(libs.plugins.ksp)
}

android {
    compileSdk = 36
    namespace 'com.omgodse.notally'

    defaultConfig {
        applicationId 'com.omgodse.notally'
        minSdk 26
        targetSdk 36
        versionCode 57
        versionName "6.2"
        resourceConfigurations += ['en', 'ca', 'cs', 'da', 'de', 'el', 'es', 'fr', 'hu', 'in', 'it', 'ja', 'ko', 'my', 'nb', 'nl', 'nn', 'pl', 'pt-rBR', 'pt-rPT', 'ro', 'ru', 'sk', 'sl', 'sv', 'tl', 'tr', 'uk', 'vi', 'zh-rCN']
        vectorDrawables.generatedDensities = []
    }

    ksp {
        arg("room.schemaLocation", "$projectDir/schemas")
    }

    buildTypes {
        debug {
            applicationIdSuffix ".debug"
        }
        release {
            crunchPngs false
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }


    buildFeatures {
        viewBinding true
        buildConfig true
    }

    packagingOptions.resources {
        excludes += ["DebugProbesKt.bin", "META-INF/**.version", "kotlin/**.kotlin_builtins", "kotlin-tooling-metadata.json"]
    }

    androidResources {
        generateLocaleConfig = true
    }
}

kotlin {
    jvmToolchain(21)
}

dependencies {
    ksp libs.androidx.room.compiler
    implementation libs.androidx.room.ktx
    implementation libs.androidx.room.runtime

    implementation libs.androidx.work.runtime

    implementation libs.androidx.navigation.ui.ktx
    implementation libs.androidx.navigation.fragment.ktx

    implementation libs.androidx.documentfile
    implementation libs.androidx.lifecycle.livedata.ktx

    implementation libs.prettytime
    implementation libs.material

    implementation libs.glide
    implementation libs.swipe.layout.android
    implementation libs.subsampling.scale.image.view.androidx
}